// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKafLwQE4pEIhpOG8Rmu5FnyGBvqtjL5k',
    appId: '1:691468657295:web:49687340ba5db561e706fa',
    messagingSenderId: '691468657295',
    projectId: 'plans-6cf22',
    authDomain: 'plans-6cf22.firebaseapp.com',
    storageBucket: 'plans-6cf22.appspot.com',
    measurementId: 'G-7XQYR346CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjyrohuojCVkg-lq6V4G2f4dOfRqyyylI',
    appId: '1:691468657295:android:478ee4b792eb7902e706fa',
    messagingSenderId: '691468657295',
    projectId: 'plans-6cf22',
    storageBucket: 'plans-6cf22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA06jK_lek0fnnB_jk08bV0K8uLS9NR4Zg',
    appId: '1:691468657295:ios:8c9034a8ed665f79e706fa',
    messagingSenderId: '691468657295',
    projectId: 'plans-6cf22',
    storageBucket: 'plans-6cf22.appspot.com',
    iosBundleId: 'com.example.plans',
  );
}
